// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/models/outbox_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 932252667448243648),
    name: 'OutboxItem',
    lastPropertyId: const obx_int.IdUid(13, 5123493633096040445),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2362349481429815674),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9083666087851580194),
        name: 'operation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1217995894384770639),
        name: 'primaryKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4226411372851406884),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7670439674733350072),
        name: 'payload',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5343986529840018196),
        name: 'response',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4971751294146327351),
        name: 'retryCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2573482479989352682),
        name: 'lastTried',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8612029913083667847),
        name: 'isSynced',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1488771190633232870),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2303132774420079456),
        name: 'endPoint',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 5123493633096040445),
        name: 'priority',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 932252667448243648),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [214461829746510662],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    OutboxItem: obx_int.EntityDefinition<OutboxItem>(
      model: _entities[0],
      toOneRelations: (OutboxItem object) => [],
      toManyRelations: (OutboxItem object) => {},
      getId: (OutboxItem object) => object.id,
      setId: (OutboxItem object, int id) {
        object.id = id;
      },
      objectToFB: (OutboxItem object, fb.Builder fbb) {
        final operationOffset = fbb.writeString(object.operation);
        final primaryKeyOffset = object.primaryKey == null
            ? null
            : fbb.writeString(object.primaryKey!);
        final urlOffset = fbb.writeString(object.url);
        final payloadOffset = object.payload == null
            ? null
            : fbb.writeString(object.payload!);
        final responseOffset = object.response == null
            ? null
            : fbb.writeString(object.response!);
        final endPointOffset = object.endPoint == null
            ? null
            : fbb.writeString(object.endPoint!);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, operationOffset);
        fbb.addOffset(3, primaryKeyOffset);
        fbb.addOffset(4, urlOffset);
        fbb.addOffset(5, payloadOffset);
        fbb.addOffset(6, responseOffset);
        fbb.addInt64(7, object.retryCount);
        fbb.addInt64(8, object.lastTried);
        fbb.addInt64(9, object.isSynced);
        fbb.addInt64(10, object.createdAt);
        fbb.addOffset(11, endPointOffset);
        fbb.addInt64(12, object.priority);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final operationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final endPointParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final primaryKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final payloadParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final responseParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final retryCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final priorityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final lastTriedParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final isSyncedParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final createdAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final object = OutboxItem(
          id: idParam,
          operation: operationParam,
          endPoint: endPointParam,
          primaryKey: primaryKeyParam,
          url: urlParam,
          payload: payloadParam,
          response: responseParam,
          retryCount: retryCountParam,
          priority: priorityParam,
          lastTried: lastTriedParam,
          isSynced: isSyncedParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [OutboxItem] entity fields to define ObjectBox queries.
class OutboxItem_ {
  /// See [OutboxItem.id].
  static final id = obx.QueryIntegerProperty<OutboxItem>(
    _entities[0].properties[0],
  );

  /// See [OutboxItem.operation].
  static final operation = obx.QueryStringProperty<OutboxItem>(
    _entities[0].properties[1],
  );

  /// See [OutboxItem.primaryKey].
  static final primaryKey = obx.QueryStringProperty<OutboxItem>(
    _entities[0].properties[2],
  );

  /// See [OutboxItem.url].
  static final url = obx.QueryStringProperty<OutboxItem>(
    _entities[0].properties[3],
  );

  /// See [OutboxItem.payload].
  static final payload = obx.QueryStringProperty<OutboxItem>(
    _entities[0].properties[4],
  );

  /// See [OutboxItem.response].
  static final response = obx.QueryStringProperty<OutboxItem>(
    _entities[0].properties[5],
  );

  /// See [OutboxItem.retryCount].
  static final retryCount = obx.QueryIntegerProperty<OutboxItem>(
    _entities[0].properties[6],
  );

  /// See [OutboxItem.lastTried].
  static final lastTried = obx.QueryIntegerProperty<OutboxItem>(
    _entities[0].properties[7],
  );

  /// See [OutboxItem.isSynced].
  static final isSynced = obx.QueryIntegerProperty<OutboxItem>(
    _entities[0].properties[8],
  );

  /// See [OutboxItem.createdAt].
  static final createdAt = obx.QueryIntegerProperty<OutboxItem>(
    _entities[0].properties[9],
  );

  /// See [OutboxItem.endPoint].
  static final endPoint = obx.QueryStringProperty<OutboxItem>(
    _entities[0].properties[10],
  );

  /// See [OutboxItem.priority].
  static final priority = obx.QueryIntegerProperty<OutboxItem>(
    _entities[0].properties[11],
  );
}
